### ISSUE TITLE
Bug: error when running unit tests

### ISSUE THREAD

**Issue by DianaIfrosa** [Andrei0872/trip-designer#20]
I have tried to run a simple **LOGIN unit test** that verifies that when a customer leaves the email field empty the login will be unsuccessful. The error that occurs is :
 
error: password authentication failed for user "Windows"

  at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
  at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
  at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
  at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)

I believe this comes from the fact that I run tests in the terminal using "npm t", and the connection with the database is not done correctly. The connection should be made using the _connConfig_ field from _Database_ class (in _Database.ts_).

**Comment by Andrei0872** [comment]
I think the problem is that the ENV variables are not set. 
They are set automatically set when the server starts due to _docker-compose_.

A quick solution would be to use something like `dotenv-safe`, [here](https://stackoverflow.com/a/43866095/9632621) would be an example.

What do you think?

**Comment by DianaIfrosa** [comment]
From the example that you send I modified "load" to "config" and now it works! Thank you 🤩
